export const translateConstants = {
	DOMESTIC_CURRENCY_ACCOUNT: 'DINARSKI',
	FOREIGN_CURRENCY_ACCOUNT: 'DEVIZNI',
	BUSINESS_ACCOUNT: 'POSLOVNI',
	BANK_ACCOUNT: 'BANKARSKI',
	CONFIRMED: 'REALIZOVANO',
	PENDING: 'U OBRADI',
	REJECTED: 'ODBIJENO',
	DENIED: 'ODBIJENO',
	EXCHANGE: 'MENJAČNICA',
	INTERNAL: 'INTERNA',
	EXTERNAL: 'EKSTERNA',
	SECURITY: 'HARTIJA OD VREDNOSTI',
};
