export const ApiRoutes = {
	auth: {
		login: '/auth/login',
		activateEmployee: '/auth/activate-employee',
		allPermissions: '/permissions/all',
		allRoles: '/roles/all',
	},
	users: {
		users: '/users',
		findAll: '/users/findAll',
		findById: '/users/findById',
		findByEmail: '/users/findByEmail',
		passwordActivation: '/users/public',
		passwordChangeInit: '/users/password-change-initialization',
		passwordChangeConf: '/users/password-change-confirmation',
		createEmployee: '/users',
		createPrivateClient: '/users/public/private-client',
		createCorporateClient: '/users/public/corporate-client',
		updateEmployee: '/users/updateEmployee',
		updatePrivateClient: '/users/updatePrivateClient',
		updateCorporateClient: '/users/updateCorporateClient',
		activateEmployee: '/users/activateEmployee',
		deactivateEmployee: '/users/deactivateEmployee',
		delete: '/users/delete',
	},
	accounts: {
		associateProfileInit: '/accounts/associate-profile-initialization',
		codeConfirmation: '/accounts/code-confirmation',
		createAccountDomestic: '/accounts/create-account/domestic',
		createAccountForeign: '/accounts/create-account/foreign',
		createAccountBusiness: '/accounts/create-account/business',
	},
	stocks: {
		findAllStocks: '/stock/all',
		findStockById: '/stock',
		findStockBySymbol: '/stock/stockSymbol',
	},
};
